name: Validação do Terraform e Cria PR para develop

on:
  workflow_call:
    inputs:
      pr_branch_name:
        description: 'Branch de destino para o PR'
        required: false
        default: 'develop'
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        description: 'AWS Access Key ID'
        required: false
      AWS_SECRET_ACCESS_KEY:
        description: 'AWS Secret Access Key'
        required: false

jobs:
  validacao-terraform:
    name: "Validação do Terraform"
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Instação Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

  criacao-pr-develop:
    name: "Criação do PR para branch ${{ inputs.pr_branch_name }}"
    runs-on: ubuntu-latest
    needs: validacao-terraform

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install GitHub CLI
        run: sudo apt-get install gh

      - name: Configure Git
        run: |
          git config --global user.email "gtbarbosa@live.com"
          git config --global user.name "gustavo-dev"

      - name: Authenticate GitHub CLI
        run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token
      
      - name: Create Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          BRANCH_NAME=$(echo "${{ github.ref }}" | sed 's/refs\/heads\///')
          gh pr create --base ${{ inputs.pr_branch_name }} --head $BRANCH_NAME --title "PR da branch: $BRANCH_NAME para a branch ${{ inputs.pr_branch_name }}" --body "PR criado automaticamente. From $BRANCH_NAME to ${{ inputs.pr_branch_name }}."
